### ISSUE TITLE
Task 6 functions review

### ISSUE THREAD

**Issue by Blocktt** [KateriSalk/Alaska_IR_Automation#4]
Potential updates to [test_function.R script](https://github.com/KateriSalk/Alaska_IR_Automation/blob/main/Code/6_Analysis/test_functions.R).

- [x] Couldn't import WQS_crosswalk (Couldn't find this file path: Data/data_analysis/AK_WQS_Crosswalk_20231025.csv). WQS crosswalk in progress?
- [x] Rename "AU_num" to "AU_ID" to more closely match AK DEC's nomenclature.
- [x] In the 'removeCat3sites', shouldn't filter(Data_Sufficient == 'No') rather than "Yes"?

For the 'timeSeries' function:
- [x] I think you could get rid of the legend because it takes up space and the information is either on the y-axis or the facet wrap header. I think you would only need to keep the legend when AU_ID >1 and Constituent >1.
- [x] Consider an option to have the y-axis be log10 transformed (scale_y_log10() in ggplot). Of course, this would add double the amount of plot code you need to write.
- [x] When AU_ID == 1, perhaps you can write the AU_ID as the title? Without it, there is no way to know to which AU the data displayed belong.

For the 'boxPlot' function:
- [x] Consider similar aesthetic upgrades as for 'timeSeries'
- [x] When AU_ID >1 and Constituent ==1, couldn't AU_ID be the x value rather than being wrapped using facet_wrap? When the number of AU_IDs input gets large, I'm not sure which one will look better. We could test that.

**Comment by KateriSalk** [comment]
Potential functions to include in the data analysis package:
- [ ] Data sufficiency evaluation
- [ ] Select AU and pollutant
- [ ] Spatial mapping of monitoring sites within AU
- [ ] Evaluation of data from multiple monitoring locations within the Au
- [ ] Comparing data against WQC crosswalk
- [ ] Visualize time series
- [ ] Visualize statistical distributions
- [ ] Summarize AU, pollutant, metadata
- [ ] Categorize assessment units for each pollutant
- [ ] Summarize impairment descriptions

Other To Do:
- [ ] Create list of complex WQS methods with no corresponding samples to run by AK DEC
- [ ] Create spreadsheet of TADA constituent names with WQS crosswalk constituents to run by AK DEC
- [ ] Create list of questions remaining on WQS crosswalk methods

**Comment by KateriSalk** [comment]
Updates for specific constituents:

- [ ] Update hardness-dependent criteria evaluation by including and treating these characteristics as equal: Hardness; Hardness, carbonate; Hardness, Ca, Mg; Total hardness
- [ ] For pH, hardness, and temp dependent criteria, use the following requirements: pH - if available during the 5-year period can be used. Hardness - if available during the 5-year period can be used. Temperature - required for the same date
- [ ] Add ammonia standard assessment. Should treat Ammonia and Ammonia-Nitrogen as synonymous

**Comment by KateriSalk** [comment]
Suggested updates to boxplot and time series functions:

- [ ] Separate plots by constituent (not facets, this could get unwieldy to fit on one page if many constituents are measured)
- [ ] Add color legend to represent different sites in the AU. Check how many max sites there are and specify that number of potential colors. Suggest grabbing hex codes from AK DEC website
- [ ] Time series plots should span entire width of the page (this should be fixed by removing facets by constituent)
